---
# Configure rabbitmq users.

- name: "Add square user."
  rabbitmq_user:
    user: square
    password: "{{ rabbitmq_user_square_password }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
  run_once: yes
  delegate_to: "{{ groups['rabbit'][0] }}"

- name: "Add (pan)opticon user."
  rabbitmq_user:
    user: pan
    password: "{{ rabbitmq_user_pan_password }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
  run_once: yes
  delegate_to: "{{ groups['rabbit'][0] }}"

- name: "Remove the default guest user."
  rabbitmq_user:
    user: guest
    state: absent
  run_once: yes
  delegate_to: "{{ groups['rabbit'][0] }}"
